### ISSUE TITLE
Can I **not** dim other windows when I'm using the minibuffer?

### ISSUE THREAD

**Issue by ghost** [gonewest818/dimmer.el#17] opened 2018-07-21 18:20 UTC
That's a great package that solves something that had been bothering me for a while, so thanks you!!

I see that you made the `dimmer-exclusion-regexp` so I can prevent a window to be dimmed, and that is awesome, but I'd also like to be able to make a particular window **not** cause the same to others when it is focused. In my case, I don't want to dim any window when I'm using the minibuffer. Is that possible right now?

Just to clarify: when I open the minibuffer, it does not dim the other windows immediately, but when I start typing. I use Ivy/Counsel. Here's [my complete environment](https://gist.github.com/mrbig033/63fd7f4f51b6a8ae379abae74c52aff2) just in case.

**Comment by sshaw** [comment] 2019-05-27 01:51
I was looking for this too. Would be a very nice feature.

**Comment by gonewest818** [comment] 2019-11-16 05:15
This is now possible with the code just merged into master, which should appear in the next update to MELPA.  I do need to update the documentation to make this new feature more obvious.

I'd appreciate some testing if you're still using `dimmer.el`.  Wait for the next MELPA build (watch the build badges on the README), and when you've updated the package you can then configure something like this:
```
      (setq dimmer-fraction 0.33)
      (setq dimmer-exclusion-predicates
            '(helm--alive-p
              window-minibuffer-p))
      (setq dimmer-exclusion-regexp-list
            '("^\\*[h|H]elm.*\\*"
              "^\\*Minibuf-[0-9]+\\*"
              "^.\\*which-key\\*$"
              "^.\\*Echo.*\\*"))
```

See how that works for you...

**Comment by gonewest818** [comment] 2019-11-16 05:18
Actually this is a duplicate of #10, and since that issue has additional content to it, I'm closing this and referring you there.

**Closed as completed by gonewest818** 2019-11-16 05:18 UTC
Labels: duplicate
